[package]
name = "airbender-guest"
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Guest-side APIs for reading inputs, committing outputs, and profiling"
readme = "README.md"

[dependencies]
airbender-core = { path = "../airbender-core", default-features = false }
airbender-codec = { path = "../airbender-codec" }
airbender-rt = { path = "../airbender-rt", default-features = false }
serde = { workspace = true, default-features = false, features = ["alloc", "derive"] }
wincode = { version = "0.5.4", default-features = false, features = ["derive", "alloc"] }

[features]
default = ["allocator-talc"]
std = ["airbender-rt/std", "serde/std"]
allocator-bump = ["airbender-rt/allocator-bump"]
allocator-talc = ["airbender-rt/allocator-talc"]
allocator-custom = ["airbender-rt/allocator-custom"]
